### ISSUE TITLE
No module named 'retrieval'

### ISSUE THREAD

**Issue by shijiangming1** [BUAADreamer/SPN4CIR#1]
Thank you for your excellent work, I meet a bug, as follows:
  
  File "/data1/sjm/ZS_CIR/SPN4CIR/zscir/data_process.py", line 11, in <module>
    from retrieval import ImageDataset, extract_image_features
ModuleNotFoundError: No module named 'retrieval'

Can you help me?

**Comment by BUAADreamer** [comment]
Sorry for missing this file, I have uploaded it. You can try to pull the latest code.
