### ISSUE TITLE
Training inexplicably interrupted

### ISSUE THREAD

**Issue by Yang-Li-Chang** [BUAADreamer/SPN4CIR#2]
Dear author,I've encountered a bug while running blip4cir/train.py. The training process terminates unexpectedly during the encoding of bank features without any error messages.
Could you please help me with this issue?
Thank you:)
![Screenshot 2024-09-20 202659](https://github.com/user-attachments/assets/43d75ff4-98e9-4d5f-8a3a-626beadf499c)

**Comment by BUAADreamer** [comment]
其他的模型您可以跑吗

**Comment by Yang-Li-Chang** [comment]
CLIP4CIR可正常跑，但BLIP模型异常中断

**Comment by BUAADreamer** [comment]
> CLIP4CIR可正常跑，但BLIP模型异常中断

可以发您的微信到我的邮箱 muller.dreamer@qq.com，我们微信联系

**Comment by BUAADreamer** [comment]
If you need to run the blip4cir and blip24cir training, try to prepare a machine with sufficient cuda memory (at least A100 40G) and RAM (300G) 

By the way, since the size of the bank is too large, there is no plan to put the bank directly on the huggingface, sorry about this
