### ISSUE TITLE
CIRR

### ISSUE THREAD

**Issue by PanXGzhu** [BUAADreamer/SPN4CIR#3]
Hello! . I am currently studying for my master degree in Wuhan University of Technology. Recently, I had the honor to read your paper.I am deeply impressed with the research content and results in IMAGE RETRIEVAL, and believe it has important reference value for my research work.After reading your paper in depth, I became very interested in the CIRR dataset you used, and I think that having access to this dataset would greatly enhance my research work. I fully understand that there are many considerations involved in the sharing of data sets, so it is important to
I would like to express my sincere gratitude and respect for the efforts you may have made.
I wonder if it is convenient for you to share this dataset.

**Comment by BUAADreamer** [comment]
You can find cirr dataset except for the image here: https://huggingface.co/datasets/BUAADreamer/cir_dataset

To make it easier for people to reproduce, I'll upload CIRR images here in two days.
