### ISSUE TITLE
Why did you use checkpoints released by the baselines as the first stage models without retrain them by your scaling dataset.

### ISSUE THREAD

**Issue by duong-bq** [BUAADreamer/SPN4CIR#4]

**Comment by BUAADreamer** [comment]
Some of the first-stage models are difficult to reproduce for various reasons, such as TGCIR, BLIP4CIR. So for the convenience of fair comparison, these models are directly used as the first-stage models in the main experiments, and the scaling of positive and negative examples are performed in the second stage.

In the ablation experiments, the SP variant is the direct first stage plus the positive examples we generated, and the effect is also improved compared to using the annotated data directly.
