### ISSUE TITLE
I run file to validate baseline in respository ABaldrati/CLIP4Cir but face problem that lack of fashionIQ images, did you face that issue?

### ISSUE THREAD

**Issue by duong-bq** [BUAADreamer/SPN4CIR#5]
Can you share FashionIq data, i didn't find source to download that dataset

**Comment by BUAADreamer** [comment]
![image](https://github.com/user-attachments/assets/7050b40e-4954-4737-8b19-4cbea0215370)

**Comment by duong-bq** [comment]
Oh, I checked and found many files in .json are not named in the images folder. However, maybe your code has handled that omission.
