### ISSUE TITLE
Visualization of Retrieval Results Using BLIP24CIR on FashionIQ Dataset

### ISSUE THREAD

**Issue by LeeHoang2710** [BUAADreamer/SPN4CIR#7]
Hi Author,

Thank you for sharing the resources and code for improving composed image retrieval tasks.
I would like to visualize the retrieval results for specific queries of BLIP24CIR model on FashionIQ dataset. Could you point out where in the repository that can generate and visualize retrieval results for a given query like this?
![image](https://github.com/user-attachments/assets/b5fce5f5-0849-40a1-bebd-a36a99f9cffb)

**Comment by BUAADreamer** [comment]
You can first try to run validate.py under every model

Then you can modify 2 functions to dump what you want, e.g. blip24cir：https://github.com/BUAADreamer/SPN4CIR/blob/fe4996e71dd464bb06fd907895a054d0daf9fa82/blip24cir/validate.py#L19C1-L94C69
