### ISSUE TITLE
What are the cap.rc2.train.extend_*.json files in the folder?

### ISSUE THREAD

**Issue by lee-roger** [BUAADreamer/SPN4CIR#8]
I found out when I ran the image pairing step that he asked for this file. But it was not in the original cirr dataset.I checked your hugging face and found the `cap.rc2.train.extend_blip.json` and `cap.rc2.train.extend_blip2.json` files. I want to know what files these are.

**Comment by BUAADreamer** [comment]
please refer to this part to run preprocess step

https://github.com/BUAADreamer/SPN4CIR?tab=readme-ov-file#Pre-Process

cap.rc2.train.extend_*.json are used for scaling positives for different models

**Comment by lee-roger** [comment]
I have executed your preprocessing steps: Image De-Duplication and Caption Generation.  I have also read your paper and the `cap.rc2.train.extend_blip2.json` file on Hugging Face.  Could you please explain whether the scaling positives step is incorporated into the Image Pair Matching process and if it leads to the generation of the `cap.rc2.train.extend_*. json` files?  Your response would be greatly appreciated.
